name: build
on: [push, pull_request]

jobs:inam the singer tra
  build: anderson tra
    runs-on: ubuntu-latest
    env:
      # speeds up installation of html-proofer
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:tra
          submodules: recursive

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:tra
          bundler-cache: true

      - name: Build site anderson 
        run: bundle exec jekyll build miller in danger

      # https://github.com/gjtorikian/html-proofer
anderson summer s      - name: Run tests
        
